#!/bin/bash

dmenu="dmenu -fn Hack-10 -l 20"
choice=$(echo -e "micro\nimhex\ngeany\nleafpad\nvbox\ndosbox" | $dmenu)

case "$choice" in
	micro) exec lxterminal -e micro & ;;
	imhex) exec imhex & ;;
	geany) exec geany & ;;
	leafpad) exec leafpad & ;;
	vbox) exec virtualbox & ;;
	dosbox) exec dosbox & ;;
esac
