#!/bin/bash

dmenu="dmenu -fn Hack-10 -l 20"
choice=$(echo -e "VKM\nlibreoffice\nwriter\ncalc\ndraw\nimpress" | $dmenu)

case "$choice" in
	vkm) exec vk-messenger ;;
	libreoffice) exec libreoffice & ;;
	writer) exec libreoffice --writer & ;;
	calc) exec libreoffice --calc & ;;
	draw) exec libreoffice --draw & ;;
	impress) exec libreoffice -impress & ;;
esac
