#!/bin/bash
filename="$(echo ~)/Изображения/$(date +%Y-%m-%e-%H-%M-%S).png"
if [ "$1" == "-s" ]; then
    maim -s $filename
    xclip -selection clipboard -t image/png -i $filename
elif [ "$1" == "-p" ]; then
    maim -s $filename
    mtpaint $filename
    xclip -selection clipboard -t image/png -i $filename
else
    maim $filename
    xclip -selection clipboard -t image/png -i $filename
fi
